clinica_pani_homepage:
    path:     /
    defaults: { _controller: clinicaPaniBundle:Default:index }
    
clinica_pani_vistametge:
    path:     /vmetge
    defaults: { _controller: clinicaPaniBundle:Metges:vistaMetge }

clinica_pani_vistapacient:
    path:     /vpacient
    defaults: { _controller: clinicaPaniBundle:Pacients:vistaPacient }
    
clinica_pani_afgrpacient:
    path:     /afgrpacient/
    defaults: { _controller: clinicaPaniBundle:Pacients:afegirPacient }

    
clinica_pani_modipacient:
    path:     /modipacient/{dni}
    defaults: { _controller: clinicaPaniBundle:Pacients:modificarPacient }
    
clinica_pani_elimpacient:
    path:     /elmnpacient/{dni}
    defaults: { _controller: clinicaPaniBundle:Pacients:eliminarPacient }

#clinica_pani_vistavisita:
#    path:     /vvisita
#    defaults: { _controller: clinicaPaniBundle:Visites:vistaVsta }
    
clinica_pani_vistavisites:
    path:     /vvisites
    defaults: { _controller: clinicaPaniBundle:Visites:vistaVisita }

clinica_pani_detallsvisita:
    path:     /dtllsvisita/{ref}
    defaults: { _controller: clinicaPaniBundle:Visites:veureDetalls }