clinica_pani_homepage:
    path:     /
    defaults: { _controller: clinicaPaniBundle:Default:index }
    
clinica_pani_vistametge:
    path:     /vmetge
    defaults: { _controller: clinicaPaniBundle:Metges:vistaMetge }
    
clinica_pani_vistavisites:
    path:     /vvisites
    defaults: { _controller: clinicaPaniBundle:Visites:vistaVisita }

clinica_pani_detallsvisita:
    path:     /dtllsvisita/{ref}
    defaults: { _controller: clinicaPaniBundle:Visites:veureDetalls }