clinica_pani_homepage:
    path:     /
    defaults: { _controller: clinicaPaniBundle:Default:index }

#·············································································
# VISTES DE LES LLISTES
#.............................................................................

clinica_pani_vistametge:
    path:     /vmetge
    defaults: { _controller: clinicaPaniBundle:Metges:vistaMetge }

clinica_pani_vistapacient:
    path:     /vpacient
    defaults: { _controller: clinicaPaniBundle:Pacients:vistaPacient }

clinica_pani_vistavisites:
    path:     /vvisites
    defaults: { _controller: clinicaPaniBundle:Visites:vistaVisita }

clinica_pani_detallsvisita:
    path:     /dtllsvisita/{ref}
    defaults: { _controller: clinicaPaniBundle:Visites:veureDetalls }
    
#·············································································
# CRUD METGE
#.............................................................................

clinica_pani_afgrmetge:
    path:     /afgrmetge
    defaults: { _controller: clinicaPaniBundle:Metges:afegirMetge }

clinica_pani_modimetge:
    path:     /modimetge/{dni}
    defaults: { _controller: clinicaPaniBundle:Metges:modificarMetge }

clinica_pani_elimmetge:
    path:     /elmnmetge/{dni}
    defaults: { _controller: clinicaPaniBundle:Metges:eliminarMetge }

#·············································································
# CRUD PACIENT
#.............................................................................

clinica_pani_afgrpacient:
    path:     /afgrpacient
    defaults: { _controller: clinicaPaniBundle:Pacients:afegirPacient }

    
clinica_pani_modipacient:
    path:     /modipacient/{dni}
    defaults: { _controller: clinicaPaniBundle:Pacients:modificarPacient }
    
clinica_pani_elimpacient:
    path:     /elmnpacient/{dni}
    defaults: { _controller: clinicaPaniBundle:Pacients:eliminarPacient }

#·············································································
# CRUD VISITA
#.............................................................................

clinica_pani_afgrvisita:
    path:     /afgrvisita
    defaults: { _controller: clinicaPaniBundle:Visites:afegirVisita }

    
clinica_pani_modivisita:
    path:     /modivisita/{ref}
    defaults: { _controller: clinicaPaniBundle:Visites:modificarVisita }
    
clinica_pani_elimvisita:
    path:     /elimvisita/{ref}
    defaults: { _controller: clinicaPaniBundle:Visites:eliminarVisita }